// Generated by https://quicktype.io

export interface Unidade {
  cgc:                         number;
  nome_Exibicao:               string;
  superior:                    number;
  naO_SEI:                     number;
  nome:                        string;
  sigla:                       string;
  cidade:                      string;
  estado:                      string;
  tipo:                        string;
  gestor:                      string;
  vJustificativaTransferencia: null;
  bDeletado:                   boolean;
  templates_Respostas:         any[];
}
