// Generated by https://quicktype.io

export interface Curva {
  idCurva_Envio:                                 number;
  apelido_Curva_Envio:                           string;
  nome_Curva_Envio:                              string;
  curva_Envio_Tranches:                          CurvaEnvioTranche[];
  solicitacaoidCurva_Envio_Dia_CheioNavigation:  any[];
  solicitacaoidCurva_Envio_Dia_NormalNavigation: any[];
}

export interface CurvaEnvioTranche {
  idCurva_Envio_Tranches:  number;
  idCurva_Envio:           number;
  hora_Envio:              string;
  tranche:                 number;
  limite_Clientes:         number;
  limite_PUSH:             number;
  idCurva_EnvioNavigation: null;
  hora_EnvioFormatado:     string;
}
