// Generated by https://quicktype.io

export interface EnviosResponse {
  idSolicitacao_Simulacao_Envio: number;
  idSolicitacao_PUSH:            number;
  idEnvio_Mensagem:              number;
  tranche:                       number;
  data:                          string;
  hora:                          { [key: string]: number };
  horaFormatado:                 string;
  homologado:                    boolean;
  quantidade:                    number;
  nome_Arquivo:                  string;
  enviado:                       boolean;
  matricula_Enviante:            string;
  quantidade_Reportada:          number;
  data_Hora_Envio:               string;
  data_Hora_Atualizacao:         string;
  bloqueado_TI:                  boolean;
  matricula_Bloqueio_TI:         string;
  data_Hora_Bloqueio:            string;
  reQ_Envio:                     string;
  gerado:                        boolean;
  parametroLote:                 number;
  cancelado:                     boolean;
  reQ_EnvioNavigation:           ReQEnvioNavigation;
  idSolicitacao_PUSHNavigation:  IDSolicitacaoPUSHNavigation;
  solicitacao_Clientes:          SolicitacaoCliente[];
}

export interface IDSolicitacaoPUSHNavigation {
  idSolicitacao_PUSH:                 number;
  wF_GECRM:                           number;
  nome_Solicitacao:                   string;
  reQ_WO_Aprovacao_Mensagem:          string;
  reQ_WO_Aprovacao_Mensagem_Texto:    string;
  idEnvio_Mensagem:                   number;
  mensagem:                           string;
  canal:                              string;
  nome_Campo1:                        string;
  nome_Campo2:                        string;
  nome_Campo3:                        string;
  nome_Campo4:                        string;
  nome_Campo5:                        string;
  idCurva_Envio_Dia_Normal:           number;
  idCurva_Envio_Dia_Cheio:            number;
  enviar_a_partir_de:                 string;
  enviar_no_maximo_ate:               string;
  enviar_SEG:                         boolean;
  enviar_TER:                         boolean;
  enviar_QUA:                         boolean;
  enviar_QUI:                         boolean;
  enviar_SEX:                         boolean;
  enviar_SAB:                         boolean;
  enviar_DOM:                         boolean;
  enviar_Horario_Inicial:             { [key: string]: number };
  enviar_Horario_Final:               { [key: string]: number };
  limitacao_Tranche:                  number;
  quantidade_Total:                   number;
  quantidade_Enviada:                 number;
  matricula_Cadastramento:            string;
  data_Cadastramento:                 string;
  autorizacao_Gestor_PUSH:            boolean;
  matricula_Autorizacao_Gestor_PUSH:  string;
  bloqueado_TI:                       boolean;
  matricula_Bloqueio_TI:              string;
  data_Hora_Bloqueio:                 string;
  data_Hora_Autorizacao:              string;
  cancelado:                          boolean;
  matricula_Cancelamento:             string;
  data_Hora_Cancelamento:             string;
  cgcDemandante:                      number;
  cgcExecutora:                       number;
  finalizado:                         boolean;
  impactos_Previstos:                 string;
  prioridade:                         number;
  quantidade_Agendada:                number;
  quantidade_Total_Restante:          number;
  canalNavigation:                    CanalNavigation;
  idCurva_Envio_Dia_CheioNavigation:  IDCurvaEnvioDiaNavigation;
  idCurva_Envio_Dia_NormalNavigation: IDCurvaEnvioDiaNavigation;
  idEnvio_MensagemNavigation:         IDEnvioMensagemNavigation;
  solicitacao_Clientes:               SolicitacaoCliente[];
  solicitacao_Simulacao_Envio:        string[];
}

export interface CanalNavigation {
  canal:       string;
  nome_Canal:  string;
  disponivel:  boolean;
  solicitacao: string[];
}

export interface IDCurvaEnvioDiaNavigation {
  idCurva_Envio:                                 number;
  apelido_Curva_Envio:                           string;
  nome_Curva_Envio:                              string;
  curva_Envio_Tranches:                          CurvaEnvioTranch[];
  solicitacaoidCurva_Envio_Dia_CheioNavigation:  string[];
  solicitacaoidCurva_Envio_Dia_NormalNavigation: string[];
}

export interface CurvaEnvioTranch {
  idCurva_Envio_Tranches:  number;
  idCurva_Envio:           number;
  hora_Envio:              { [key: string]: number };
  tranche:                 number;
  limite_Clientes:         number;
  limite_PUSH:             number;
  idCurva_EnvioNavigation: string;
}

export interface IDEnvioMensagemNavigation {
  idEnvio_Mensagem:     number;
  mensagem1:            string;
  data_Inicio:          string;
  data_Fim:             string;
  tranches:             number;
  push_Enviados:        number;
  apelido:              string;
  ativo:                boolean;
  enviados:             number;
  faltam:               number;
  appCaixa:             boolean;
  caixaTem:             boolean;
  mensagemRegex:        string;
  monitoração_Producao: string;
  caixA_Tem:            boolean;
  cartão:               boolean;
  crédito:              boolean;
  pre_Autorizado:       boolean;
  envio_CPF:            EnvioCPF[];
  envio_Tranche:        EnvioTranche[];
  solicitacao:          string[];
}

export interface EnvioCPF {
  idEnvio_CPF:                number;
  idEnvio_Mensagem:           number;
  idEnvio_Tranche:            number;
  cpf:                        number;
  qtd:                        number;
  v1:                         string;
  canal:                      string;
  cpfNavigation:              CpfNavigation;
  idEnvio_MensagemNavigation: string;
  idEnvio_TrancheNavigation:  EnvioTranche;
}

export interface CpfNavigation {
  cpf:           number;
  tem_App_CAIXA: boolean;
  tem_CAIXA_Tem: boolean;
  qtd:           number;
  base_Origem:   number;
  envio_CPF:     string[];
}

export interface EnvioTranche {
  idEnvio_Tranche:            number;
  idEnvio_Mensagem:           number;
  tranche:                    number;
  data_Envio:                 string;
  hora_Envio:                 { [key: string]: number };
  nome_Do_Arquivo:            string;
  limite_Clientes:            number;
  limite_PUSH:                number;
  quantidade_PUSH_Reportado:  number;
  enviado:                    boolean;
  retorno:                    number;
  milisegundos:               number;
  parametroLote:              number;
  naoExecutado:               boolean;
  idEnvio_MensagemNavigation: string;
  envio_CPF:                  string[];
}

export interface SolicitacaoCliente {
  idSolicitacao_Cliente:                   number;
  idSolicitacao_PUSH:                      number;
  idSolicitacao_Simulacao_Envio:           number;
  cpf:                                     number;
  campo1:                                  string;
  campo2:                                  string;
  campo3:                                  string;
  campo4:                                  string;
  campo5:                                  string;
  agendado:                                boolean;
  enviado:                                 boolean;
  idSolicitacao_PUSHNavigation:            string;
  idSolicitacao_Simulacao_EnvioNavigation: string;
}

export interface ReQEnvioNavigation {
  reQ_Envio:                   string;
  wO_Envio:                    string;
  historico:                   string;
  abertura:                    string;
  fechamento:                  string;
  solicitacao_Simulacao_Envio: string[];
}
