// Generated by https://quicktype.io

export interface FilaResponse {
  id:         number;
  wf:         number;
  data:       string;
  nome:       string;
  prioridade: number;
  idm:        number;
  mensagem:   string;
  canal:      string;
  cn:         number;
  cr:         number;
  total:      number;
  enviada:    number;
  agendado:   number;
  fila:       number;
  cancelado:  boolean;
  finalizado: boolean;
}
