// Generated by https://quicktype.io

export interface TipoCategoriaSolicitacao {
  tipo_Categoria_Solicitacao1:        number;
  apelido_Tipo_Categoria_Solicitacao: string;
  nome_Tipo_Categoria_Solicitacao:    string;
  minimo_Tranche:                     number;
  maximo_Tranche:                     number;
  ordem:                              number;
  idCurva_Envio:                      number;
  idCurva_Envio_2:                    number;
  idCurva_Envio_3:                    number;
  idCurva_EnvioNavigation:            any;
  idCurva_Envio_2Navigation:          any;
  idCurva_Envio_3Navigation:          any;
  solicitacao:                        any[];
}
