// Generated by https://quicktype.io

export interface TemplateRespostaResponse {
    $id:     string;
    $values: TemplateResposta[];
}

export interface TemplateResposta {
    $ref?:                       string;
    $id?:                        string;
    vTemplateResposta?:          string;
    vResposta?:                  string;
    vAcao?:                      VAcao;
    cgC_Tranferencia?:           number;
    cgC_TranferenciaNavigation?: CGCTranferenciaNavigation;
    chamados?:                   any;
    dLastUse?:                   string;
}


export enum VAcao {
    Fechar = "Fechar!",
    Transferir = "Transferir!",
}

export interface CGCTranferenciaNavigation {
    $id:                          string;
    cgc:                          number;
    nome_Exibicao:                string;
    superior:                     number;
    naO_SEI:                      number;
    nome:                         string;
    sigla:                        string;
    cidade:                       string;
    estado:                       string;
    tipo:                         string;
    gestor:                       string;
    vJustificativaTransferencia?: string;
    templates_Resposta:           TemplateResposta;
}

export interface AaValue {
    $id?:                        string;
    vTemplateResposta?:          string;
    vAssunto?:                   string;
    vResposta?:                  string;
    vAcao?:                      VAcao;
    chamados?:                   any;
    dLastUse?:                   string;
    cgC_Tranferencia?:           number;
    cgC_TranferenciaNavigation?: any;
    $ref?:                       string;
}

