// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

// export interface ResponseChamadoMinimo {
//     $id:     string;
//     $values: ChamadoMinimo[];
// }

export interface ResponseChamadoMinimo extends Array<ChamadoMinimo>{
    
};

export interface ChamadoMinimo {
    $id:                      string;
    vOrigem:                  VOrigem;
    idChamado:                number;
    iIdentificacaoChamado:    number;
    vCPF_CNPJ_Solicitante:    null | string;
    vNomeSolicitante:         string;
    vTipoOcorrencia:          null | string;
    dDataHoraAbertura:        null | string;
    dDataVencimento:          null | string;
    dDataMaximaTransferencia: null | string;
    vNatureza:                null | string;
    vAssunto:                 string;
    vMotivo:                  null | string;
    vItem:                    null | string;
    vSituacaoGECDI:           VSituacaoGECDI;
    vApelidoAtendente:        null | string;
    vTemplateResposta?:       null | string;
    vAcao?:                   null | string;
    bFoiTratado:             boolean;
    vApelidoAtendenteTratou: string;
    cUsuario?:                        string;
}

// Generated by https://quicktype.io
export interface Chamado {
    $id:                              string;
    idChamado:                        number;
    vOrigem:                          VOrigem;
    iIdentificacaoChamado:            number;
    vTipoOcorrencia:                  null | string;
    vTipoOrigem?:                     string;
    vNatureza?:                       null | string;
    vAssunto:                         string;
    vItem?:                           string;
    vMotivo?:                         string;
    vNomeSolicitante:                 string;
    vManifesto:                       string;
    vSituacao?:                       null | string;
    bDetalheCapturado:                boolean;
    dDataVencimento:                  string;
    bFechado:                         boolean;
    dDataHoraAbertura:                string;
    vResposta?:                       string;
    iReabertura:                      number;
    vMovimentacoes?:                  string;
    dAtualizacao:                     string;
    idGrupo:                          number;
    idTipoRespostaPadrao:             number;
    bReaberto:                        boolean;
    bFoiFechadoAutomatico:            boolean;
    vApelidoAtendente?:               string;
    vSituacaoGECDI:                   VSituacaoGECDI;
    distribuicao_Chamados:            null | object;
    vWorkOrderID?:                    string;
    vREQ?:                            string;
    dDataMaximaTransferencia?:        string;
    vTelefones?:                      string;
    vCPF_CNPJ_Solicitante?:           string;
    iCPF_CNPJ_Solicitante?:           number;
    vEmail?:                          string;
    vComentario?:                     string;
    dDataPrimeiraAcaoAutomatico?:     string;
    dDataUltimoAcaoAutomatico?:       string;
    vUltimaAcaoAplicada?:             string;
    vUltimoTemplateRespostaAplicada?: string;
    dDiaUltimoAcaoAutomatico?:        string;
    vUltimaRespostaEnviada?:          string;
    vTemplateResposta?:               string;
    vAcao?:                           string;
    bFoiTratado:                      boolean;
    vApelidoAtendenteTratou:          string;
    dDataHoraTratamento:              string;
    cUsuario?:                        string;
}

export enum VOrigem {
    Atender = "ATENDER",
    Servicos = "SERVICOS",
}

export enum VSituacaoGECDI {
    Empty = "",
    NãoTransferir = "Não Transferir",
    VenceHoje = "Vence Hoje",
    VenceHojeNãoTransferir = "Vence Hoje / Não Transferir",
    Vencida = "Vencida",
    VencidaNãoTransferir = "Vencida / Não Transferir",
    ÚltimoDiaParaTransferir = "Último dia para transferir",
}
