// Generated by https://quicktype.io

export class User {
  id:               number;
  name:             string;
  photo:            string;
  username:         string;
  token:            string;
  user:             UserClass;
  codFuncao:        string;
  funcao:           null;
  lotacaoFisica:    string;
  lotacaoSigla:     string;
  lotacaoNome:      string;
  lotacaoTipo:      string;
  apelidoAtendente: string;

  public get e_admin() {
    return this.user.idRole == 1;
  }

}

export interface UserClass {
  idUsuario:        number;
  cUsuario:         string;
  nome:             null;
  cgc:              null;
  idRole:           number;
  idRoleNavigation: IDRoleNavigation;
  role:             number;
}

export interface IDRoleNavigation {
  idRole:                     number;
  role:                       string;
  nome_Role:                  string;
  rota:                       string;
  ordem:                      number;
  tem_Permissao_Geral:        boolean;
  e_Admin:                    boolean;
  pode_Marcar_Envio:          boolean;
  pode_Geranciar_Simulacao:   boolean;
  pode_Ver_Relatorio:         boolean;
  pode_Gerenciar_Solicitacao: boolean;
  pode_Gerenciar_Envios:      boolean;
  pode_Gerenciar_Curvas:      boolean;
  pode_Suspender_Envios:      boolean;
  usuario:                    null[];
}
