// Generated by https://quicktype.io

export interface Usuario {
  idUsuario:        number;
  cUsuario:         string;
  nome:             string;
  cgc:              number;
  idRole:           number;
  role:             number;
}


export interface IDRoleNavigation {
  idRole:                     number;
  role:                       any;
  nome_Role:                  string;
  ordem:                      number;
  rota:                       string;
  tem_Permissao_Geral:        boolean;
  e_Admin:                    boolean;
  pode_Marcar_Envio:          boolean;
  pode_Geranciar_Simulacao:   boolean;
  pode_Ver_Relatorio:         boolean;
  pode_Gerenciar_Solicitacao: boolean;
  pode_Gerenciar_Envios:      boolean;
  pode_Gerenciar_Curvas:      boolean;
  pode_Suspender_Envios:      boolean;
  usuario:                    [];
}
